from typing import List, Tuple

CATALYST_COLORS = {
    "earnings": "#16a34a",
    "news": "#2563eb",
    "analyst": "#7c3aed",
    "macro": "#b45309",
    "other": "#6b7280",
}


def format_brief(date: str, headlines: List[dict], stock_picks: List[dict], tldr: str = "", portfolio: dict = None) -> Tuple[str, str]:
    markdown = _build_markdown(date, headlines, stock_picks, tldr, portfolio)
    html = _build_html(date, headlines, stock_picks, tldr, portfolio)
    return markdown, html


def _build_markdown(date: str, headlines: List[dict], stock_picks: List[dict], tldr: str = "", portfolio: dict = None) -> str:
    lines = [
        f"# Daily Market Brief — {date}",
        "",
        f"*Generated {date} PT by Claude Routine*",
        "",
        "---",
        "",
    ]
    if tldr:
        lines += [
            "## TL;DR",
            "",
            tldr,
            "",
            "---",
            "",
        ]
    if portfolio:
        s = portfolio.get("summary", {})
        pnl = s.get("total_unrealized_pnl", 0)
        pnl_pct = s.get("total_unrealized_pnl_pct", 0)
        pnl_sign = "+" if pnl >= 0 else ""
        lines += [
            "## My Portfolio",
            "",
            f"**Invested:** ${s.get('total_invested', 0):,.2f} | "
            f"**Value:** ${s.get('total_current_value', 0):,.2f} | "
            f"**P&L:** {pnl_sign}${pnl:,.2f} ({pnl_sign}{pnl_pct * 100:.2f}%)",
            "",
        ]
        for h in portfolio.get("holdings", []):
            t = h["trade"]
            upnl = h.get("unrealized_pnl", 0)
            upnl_pct = h.get("unrealized_pnl_pct", 0)
            sign = "+" if upnl >= 0 else ""
            lines += [
                f"- **{t['symbol']}** — {t['shares']} sh @ ${t['buy_price']:.2f} → "
                f"${h['current_price']:.2f} | {sign}${upnl:.2f} ({sign}{upnl_pct * 100:.2f}%)",
            ]
        lines += ["", "---", ""]
    lines += [
        "## Top 5 Macro Headlines",
        "",
    ]
    for i, h in enumerate(headlines, 1):
        lines += [
            f"### {i}. [{h.get('headline', '')}]({h.get('url', '#')})",
            f"*{h.get('source', '')}* — {h.get('published_at', '')}",
            "",
            h.get("summary", ""),
            "",
        ]
    lines += [
        "---",
        "",
        "## Top 5 Stock Picks",
        "",
    ]
    for p in stock_picks:
        lines += [
            f"### **{p.get('ticker', '')}** — {p.get('company', '')}",
            f"*Price: {p.get('current_price', '')} | Catalyst: `{p.get('catalyst_type', '')}`*",
            "",
            p.get("reasoning", ""),
            "",
        ]
    lines += [
        "---",
        "",
        "*⚠️ Not investment advice. For informational purposes only.*",
        "",
        f"*Generated by Claude Routine on {date}*",
    ]
    return "\n".join(lines)


def _build_portfolio_html(portfolio: dict) -> str:
    if not portfolio:
        return ""
    s = portfolio.get("summary", {})
    invested = s.get("total_invested", 0)
    value = s.get("total_current_value", 0)
    pnl = s.get("total_unrealized_pnl", 0)
    pnl_pct = s.get("total_unrealized_pnl_pct", 0)
    divs = s.get("total_dividends", 0)

    rows = ""
    for h in portfolio.get("holdings", []):
        t = h["trade"]
        upnl = h.get("unrealized_pnl", 0)
        upnl_pct = h.get("unrealized_pnl_pct", 0)
        color = "#16a34a" if upnl >= 0 else "#dc2626"
        sign = "+" if upnl >= 0 else ""
        rows += f"""
          <tr style="border-top:1px solid #e5e7eb;">
            <td style="padding:8px 12px;font-weight:700;color:#111827;">{t['symbol']}</td>
            <td style="padding:8px 12px;color:#6b7280;">{t['shares']} sh</td>
            <td style="padding:8px 12px;color:#6b7280;">${t['buy_price']:.2f} → ${h['current_price']:.2f}</td>
            <td style="padding:8px 12px;text-align:right;color:{color};font-weight:600;">
              {sign}${upnl:.2f}<br>
              <span style="font-size:11px;font-weight:400;">({sign}{upnl_pct * 100:.2f}%)</span>
            </td>
          </tr>"""

    pnl_color = "#16a34a" if pnl >= 0 else "#dc2626"
    pnl_sign = "+" if pnl >= 0 else ""

    return f"""
    <div style="padding:24px 40px;">
      <h2 style="margin:0 0 16px;font-size:18px;font-weight:700;color:#111827;
                 border-bottom:2px solid #111827;padding-bottom:8px;">My Portfolio</h2>
      <div style="display:flex;gap:16px;margin-bottom:16px;flex-wrap:wrap;">
        <div style="flex:1;min-width:120px;background:#f9fafb;border-radius:8px;padding:12px 16px;">
          <div style="font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px;">Invested</div>
          <div style="font-size:18px;font-weight:700;color:#111827;">${invested:,.2f}</div>
        </div>
        <div style="flex:1;min-width:120px;background:#f9fafb;border-radius:8px;padding:12px 16px;">
          <div style="font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px;">Current Value</div>
          <div style="font-size:18px;font-weight:700;color:#111827;">${value:,.2f}</div>
        </div>
        <div style="flex:1;min-width:120px;background:#f9fafb;border-radius:8px;padding:12px 16px;">
          <div style="font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px;">Unrealized P&amp;L</div>
          <div style="font-size:18px;font-weight:700;color:{pnl_color};">{pnl_sign}${pnl:,.2f}</div>
          <div style="font-size:12px;color:{pnl_color};">{pnl_sign}{pnl_pct * 100:.2f}%</div>
        </div>
        {f'<div style="flex:1;min-width:120px;background:#f9fafb;border-radius:8px;padding:12px 16px;"><div style="font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px;">Dividends</div><div style="font-size:18px;font-weight:700;color:#16a34a;">${divs:,.2f}</div></div>' if divs > 0 else ''}
      </div>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f9fafb;">
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;">Symbol</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;">Shares</th>
            <th style="padding:8px 12px;text-align:left;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;">Buy → Current</th>
            <th style="padding:8px 12px;text-align:right;font-size:11px;color:#9ca3af;text-transform:uppercase;letter-spacing:.05em;">P&amp;L</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
    </div>
    <div style="height:8px;background:#f3f4f6;"></div>"""


def _fmt_pnl(val: float, pct: float) -> str:
    sign = "+" if val >= 0 else ""
    color = "#16a34a" if val >= 0 else "#dc2626"
    return f'<span style="color:{color};font-weight:600;">{sign}${val:,.2f} ({sign}{pct * 100:.2f}%)</span>'


def _build_html(date: str, headlines: List[dict], stock_picks: List[dict], tldr: str = "", portfolio: dict = None) -> str:
    headline_rows = ""
    for i, h in enumerate(headlines, 1):
        url = h.get("url", "#")
        headline = h.get("headline", "")
        source = h.get("source", "")
        published = h.get("published_at", "")
        summary = h.get("summary", "")
        headline_rows += f"""
        <div style="margin-bottom:24px;padding-bottom:24px;border-bottom:1px solid #e5e7eb;">
          <div style="font-size:13px;color:#6b7280;margin-bottom:4px;">
            {i}. {source} &mdash; {published}
          </div>
          <a href="{url}" style="font-size:17px;font-weight:600;color:#111827;text-decoration:none;line-height:1.4;">
            {headline}
          </a>
          <p style="margin:8px 0 0;font-size:14px;color:#374151;line-height:1.6;">{summary}</p>
        </div>"""

    pick_rows = ""
    for p in stock_picks:
        ticker = p.get("ticker", "")
        company = p.get("company", "")
        price = p.get("current_price", "")
        catalyst = p.get("catalyst_type", "other")
        reasoning = p.get("reasoning", "")
        color = CATALYST_COLORS.get(catalyst, CATALYST_COLORS["other"])
        pick_rows += f"""
        <div style="margin-bottom:24px;padding:16px;background:#f9fafb;border-radius:8px;border-left:4px solid {color};">
          <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px;">
            <span style="font-size:20px;font-weight:700;color:#111827;">{ticker}</span>
            <span style="font-size:15px;color:#6b7280;">{company}</span>
            <span style="margin-left:auto;font-size:13px;font-weight:600;color:{color};
                         background:{color}18;padding:2px 10px;border-radius:99px;">{catalyst}</span>
          </div>
          <div style="font-size:13px;color:#6b7280;margin-bottom:8px;">Price: {price}</div>
          <p style="margin:0;font-size:14px;color:#374151;line-height:1.6;">{reasoning}</p>
        </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Daily Market Brief — {date}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px;margin:32px auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1);">

    <!-- Header -->
    <div style="background:#111827;padding:32px 40px;">
      <div style="font-size:12px;font-weight:600;letter-spacing:.1em;color:#9ca3af;text-transform:uppercase;margin-bottom:8px;">
        Claude Routine
      </div>
      <h1 style="margin:0;font-size:26px;font-weight:700;color:#ffffff;">
        Daily Market Brief
      </h1>
      <div style="margin-top:8px;font-size:14px;color:#9ca3af;">{date} &mdash; US Markets</div>
    </div>

    <!-- TLDR -->
    {f'''<div style="padding:24px 40px;background:#f0f9ff;border-left:4px solid #2563eb;margin:0;">
      <div style="font-size:11px;font-weight:700;letter-spacing:.08em;color:#2563eb;
                  text-transform:uppercase;margin-bottom:8px;">TL;DR</div>
      <p style="margin:0;font-size:15px;color:#1e3a5f;line-height:1.7;">{tldr}</p>
    </div>''' if tldr else ''}

    <!-- Portfolio -->
    {_build_portfolio_html(portfolio) if portfolio else ''}

    <!-- Headlines -->
    <div style="padding:32px 40px;">
      <h2 style="margin:0 0 24px;font-size:18px;font-weight:700;color:#111827;
                 border-bottom:2px solid #111827;padding-bottom:8px;">
        Top 5 Macro Headlines
      </h2>
      {headline_rows}
    </div>

    <!-- Divider -->
    <div style="height:8px;background:#f3f4f6;"></div>

    <!-- Stock Picks -->
    <div style="padding:32px 40px;">
      <h2 style="margin:0 0 24px;font-size:18px;font-weight:700;color:#111827;
                 border-bottom:2px solid #111827;padding-bottom:8px;">
        Top 5 Stock Picks
      </h2>
      {pick_rows}
    </div>

    <!-- Footer -->
    <div style="background:#f9fafb;padding:24px 40px;border-top:1px solid #e5e7eb;">
      <p style="margin:0;font-size:12px;color:#9ca3af;line-height:1.6;">
        ⚠️ <strong>Not investment advice.</strong> This brief is generated automatically
        by Claude Routine for informational purposes only. Past performance is not indicative
        of future results. Always do your own research before making investment decisions.
      </p>
      <p style="margin:8px 0 0;font-size:12px;color:#d1d5db;">
        Generated by Claude Routine on {date}
      </p>
    </div>

  </div>
</body>
</html>"""
